### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thekip** [nogorilla/angular-cc-library#65]
## Milestone 2.0.0:

- [x] Build to [Angular Package Format (APF)](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit)
- [x] Compatibility with Angular Ivy
- [ ] Allow extending cards list https://github.com/nogorilla/angular-cc-library/issues/46
- [ ] Export directives with basic API https://github.com/nogorilla/angular-cc-library/issues/45

## Next milestone:

- [ ] Split validators to general-purpose pure functions and angular-specific validators
- [ ] Tree-shakeability (probably introduce breaking changes)
- [ ] Remove `required` validation from validators

## Project maintenance:

- [ ] setup automatic workflows for testing
- [ ] switch to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] add more examples in Readme (how to get card scheme in component class)
- [ ] provide recommendations in readme about autocomplete attributes and `inputmode` attribute
- [ ] setup badges
- [ ] deploy demo project somewhere
- [ ] setup badges in readme

## Code quality: 

- [x] Enable strict mode in typescript
- [x] Setup linting with recommended rules
- [ ] Cover with unit test not covered parts
- [ ] cover with e2e tests demo application

**Comment by thekip** [comment]
@nogorilla hey I want to set up some project automation according to the roadmap, but I need administrators privileges for that. I tried to reach you using email from package.json, but looks like this address is dead. please contact me via [email](mailto:ty@time.sc) and we discuss how to proceed
